//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2010.03.05 at 12:27:35 PM MEZ
//

package de.bht.jvr.collada14;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * The InputLocalOffset type is used to represent indexed inputs that can only
 * reference resources declared in the same document.
 * <p>
 * Java class for InputLocalOffset complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InputLocalOffset">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="offset" use="required" type="{http://www.collada.org/2005/11/COLLADASchema}uint" />
 *       &lt;attribute name="semantic" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="source" use="required" type="{http://www.collada.org/2005/11/COLLADASchema}URIFragmentType" />
 *       &lt;attribute name="set" type="{http://www.collada.org/2005/11/COLLADASchema}uint" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputLocalOffset")
public class InputLocalOffset {

    @XmlAttribute(required = true)
    protected BigInteger offset;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String semantic;
    @XmlAttribute(required = true)
    protected String source;
    @XmlAttribute
    protected BigInteger set;

    /**
     * Gets the value of the offset property.
     * 
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getOffset() {
        return offset;
    }

    /**
     * Gets the value of the semantic property.
     * 
     * @return possible object is {@link String }
     */
    public String getSemantic() {
        return semantic;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getSet() {
        return set;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return possible object is {@link String }
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setOffset(BigInteger value) {
        offset = value;
    }

    /**
     * Sets the value of the semantic property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setSemantic(String value) {
        semantic = value;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setSet(BigInteger value) {
        set = value;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setSource(String value) {
        source = value;
    }

}
