//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2010.03.05 at 12:27:35 PM MEZ
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.collada.org/2005/11/COLLADASchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.bht.jvr.collada14;

